version: "3.9"

services:
  db:
    container_name: jsbtodoproddata
    image: mysql:8.1.0
    restart: on-failure
    #.env is expected as name and located in root folder
    env_file: 
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    healthcheck:
      test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - jsbtodoproddatavol:/var/lib/mysql
        #- ./dockerinit/jsbtodoschema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jsbtodoproddatanetwork

  app:
    container_name: jsbtodorest
    depends_on:
      db:
        condition: service_healthy
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    #.env is expected as name and located in root folder
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      MYSQL_HOST: jsbtodoproddata
      MYSQL_PORT: $MYSQL_DOCKER_PORT
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - jsbtodoproddatanetwork

volumes:
  jsbtodoproddatavol:

networks:
  jsbtodoproddatanetwork:
