version: '3.8'

services:     
  db:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'jspringtodo'
      MYSQL_USER: 'javaspringtodo'
        #double $$ for escaping $ character
      MYSQL_PASSWORD: /run/secrets/dba_mysql
      # Password for root access
      MYSQL_ROOT_PASSWORD: /run/secrets/admin_mysql
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '13306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    container_name: mysqldocker
    networks:
      - jsbtodorest
    volumes:
      - jspringtodo-mysqlvol:/var/lib/mysql
    secrets:
      - dba_mysql
      - admin_mysql

  springboot-todorest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    container_name: jsbtodorestdocker
    networks:
      - jsbtodorest
    depends_on:
      - db
        #environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://localhost:13306/jspringtodo?allowPublicKeyRetrieval=true&useSSL=false
      #SPRING_DATASOURCE_USERNAME: javaspringtodo
      #SPRING_DATASOURCE_PASSWORD: jspringT0D0$$
      #SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  jspringtodo-mysqlvol:

secrets:
  dba_mysql:
    file: ./dba_mysql.txt
  admin_mysql:
    file: ./admin_mysql.txt

networks:
  jsbtodorest:
    driver: bridge
