version: '3.8'

services:
  mysqldocker:
    image: mysql:8.1.0
    restart: always
    env_file:
      - ./dockerinit/.envmysql
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '13306:3306'
    container_name: mysqldocker
    networks:
      - mysqldockernetwork
    volumes:
      - jsbtododata:/var/lib/mysql
      - ./dockerinit/jsbtodoschema.sql:/docker-entrypoint-initdb.d/init.sql

  jsbtodorest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    container_name: jsbtodorestdocker
    networks:
      - mysqldockernetwork
    depends_on:
      - mysqldocker

volumes:
  jsbtododata:

networks:
  mysqldockernetwork:
    name: mysqldockernetwork
