version: '3.3'

services:
  db:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: 'jspringtodo'
      MYSQL_USER: 'javaspringtodo'
        #double $$ for escaping $ character
      MYSQL_PASSWORD: 'jspringT0D0$$'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'db43uskAdY11'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '13306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    container_name: mysql-docker-local
    networks:
      - jsbtodorest
    volumes:
      - jspringtodo-mysqlvol: /var/lib/mysql

volumes:
  jspringtodo-mysqlvol:

networks:
  jsbtodorest:
  driver: bridge
