version: "3.8"

services:
  mysqldb:
    image: mysql:8.1.0
    restart: on-failure
    #.env is expected as name and located in root folder
    env_file: 
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - jsbtododata:/var/lib/mysql
        #- ./dockerinit/jsbtodoschema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jsbtodorestnetwork

  jsbtodorest:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
        #restart: on-failure

    #.env is expected as name and located in root folder
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQL_USER",
        "spring.datasource.password" : "$MYSQL_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.dll-auto" : "update"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - jsbtodorestnetwork

volumes:
  jsbtododata:

networks:
  jsbtodorestnetwork:
