version: "3.9"

services:
  db:
    container_name: jsbtodotest
    image: mysql:8.1.0
    restart: on-failure
    #.env is expected as name and located in root folder
    env_file:
      - ./.env 
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    healthcheck:
      test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - jsbtodotestdata:/var/lib/mysql
        #- ./dockerinit/jsbtodoschema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jsbtodotestnetwork

volumes:
  jsbtodotestdata:

networks:
  jsbtodotestnetwork:
