# Docker profile configuration
spring:
  datasource:
    url: jdbc:mysql://mysqldev:3306/${DB_NAME_PRODUCTION:jsbtododev}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

# Docker logging
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    com.bytestree.restful: DEBUG 