# Docker profile configuration
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/{DB_NAME_PRODUCTION:jsbtododev}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
    generate-ddl: true

# Docker-specific JWT configuration
jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION_MS} # 8 hours
  refresh: ${JWT_REFRESH}

# Docker seeding (disabled for production)
seed:
  development: ${SEED_DEVELOPMENT:false}
  production: ${SEED_PRODUCTION:false}

server:
  port: ${DOCKER_INTERNAL_PORT:8080}

# Docker logging
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    com.bytestree.restful: DEBUG 