# Docker profile configuration
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/todo_prod?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:todo_user}
    password: ${DB_PASSWORD:todo_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
    generate-ddl: true

# Docker-specific JWT configuration
jwt:
  secret: ${JWT_SECRET:dockerSecretKeyForProductionOnly123456789}
  expiration-milliseconds: ${JWT_EXPIRATION:28800000} # 8 hours

# Docker seeding (disabled for production)
seed:
  development: false
  production: false

# Docker logging
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    com.bytestree.restful: DEBUG 