# Base application configuration
spring:
  profiles:
    active: development
  application:
    name: todo-app

# Common server configuration
server:
  port: 8011

# Common logging configuration
logging:
  level:
    org.springframework.security: DEBUG
    com.hftamayo.java.todo: DEBUG

# Common JWT configuration (will be overridden by profiles)
jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentOnly}
  expiration-milliseconds: ${JWT_EXPIRATION:28800000} # 8 hours default

# Common seeding configuration
seed:
  development: false
  production: false

# Common test user configuration
test:
  user:
    email: test@example.com
    password: password123 

app:
  environment: production
  debug:
    jwt: false     