# Development profile configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/todo_dev?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false

# Development-specific JWT configuration
jwt:
  secret: ${JWT_SECRET:devSecretKeyForDevelopmentOnly123456789}
  expiration-milliseconds: ${JWT_EXPIRATION:28800000} # 8 hours

# Development seeding
seed:
  development: true
  production: false

# Development logging
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 