package com.hftamayo.java.todo.config;

import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.info.BuildProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.Instant;
import java.util.Properties;

/**
 * Configuration class for build information.
 * Ensures BuildProperties bean is available even if not generated by Maven plugin.
 */
@Configuration
public class BuildInfoConfig {

    /**
     * Creates a fallback BuildProperties bean if the Maven plugin doesn't generate one.
     * This prevents the application from failing to start when BuildProperties is missing.
     */
    @Bean
    @ConditionalOnMissingBean(BuildProperties.class)
    public BuildProperties fallbackBuildProperties() {
        Properties properties = new Properties();
        properties.setProperty("version", "0.1.5");
        properties.setProperty("name", "todo-app");
        properties.setProperty("time", Instant.now().toString());
        properties.setProperty("group", "com.hftamayo.java.todo");
        properties.setProperty("artifact", "todo-app");
        
        return new BuildProperties(properties);
    }
}
